GET http://localhost:3001/
###
GET http://localhost:3001/species/60cb85b5317ed2370ca7d605
###
GET http://localhost:3001/species

###

POST http://localhost:3001/species
Content-Type: application/json

{
    "name":"Blue Tiger",
    "category":"Mamifero"
}

###
DELETE http://localhost:3001/species/60cb7fe5ddb9272db4fceb1d

###
PATCH http://localhost:3001/60cb7fe5ddb9272db4fceb1d
Content-Type: application/json

{
    "name":"Hey"
}